#!/usr/bin/perl -w
# -*- perl -*-

#
# $Id: Makefile.PL,v 1.8 2009/05/31 15:21:46 k_wittrock Exp $
# Author: Slaven Rezic
#
# Copyright (C) 2001-2009 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: srezic@cpan.org
# WWW:  http://user.cs.tu-berlin.de/~eserte/
#

use ExtUtils::MakeMaker;

WriteMakefile
  (
   'NAME'	   => 'Tk::PathEntry',
   'VERSION_FROM'  => 'PathEntry.pm',
   'PREREQ_PM'     => { Tk => 800.020 },
   'NO_META'       => 1,

   'dist'          => {'POSTOP'=>'-$(CHMOD) 644 $(DISTVNAME).tar$(SUFFIX)'},

   'ABSTRACT_FROM' => '',
   'AUTHOR'        => 'Slaven Rezic (srezic@cpan.org)',
  );

sub MY::postamble {
    my $postamble = "";

    if (defined $ENV{USER} && $ENV{USER} eq 'eserte' && $^O =~ /bsd/i && -f "../../perl.release.mk") {
	$postamble .= <<'EOF';

.include "../../perl.release.mk"
.include "../../perl.cvs.mk"

EOF
    }

    $postamble;
}

__END__
